# Generated by Django 3.1.7 on 2021-04-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='device_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='mean',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='mode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='uuid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
