# Generated by Django 3.2 on 2021-05-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_auto_20210422_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='hr_mean',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='hrv_pnn50',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='hrv_rmssd',
            field=models.CharField(default='', max_length=50),
        ),
    ]
