# Generated by Django 3.2 on 2021-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_auto_20210608_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='status',
            new_name='status_basic',
        ),
        migrations.AddField(
            model_name='response',
            name='status_sliding',
            field=models.CharField(default='', max_length=50),
        ),
    ]
