# Generated by Django 3.2 on 2021-06-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0009_auto_20210608_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(default='', max_length=50)),
                ('uuid', models.CharField(default='', max_length=50)),
                ('short_hand', models.CharField(default='', max_length=50)),
                ('event_label', models.CharField(default='', max_length=50)),
                ('event_value', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
