# Generated by Django 3.2 on 2021-06-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_eventlabel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlabel',
            old_name='event_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='eventlabel',
            old_name='event_value',
            new_name='value',
        ),
    ]
