# Generated by Django 3.2 on 2021-06-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_auto_20210609_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlabel',
            old_name='label',
            new_name='name',
        ),
    ]
