# Generated by Django 3.2 on 2021-06-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0012_rename_label_eventlabel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='', max_length=50)),
                ('uuid', models.CharField(default='', max_length=50)),
                ('frequency', models.IntegerField(default=0)),
                ('baseline_size', models.IntegerField(default=0)),
                ('hr_threshold', models.FloatField(default=0.0)),
                ('hrv_threshold', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
